version: '3'
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=kohlantstats -user=root -password=P@ssw0rd -connectRetries=60 migrate
    volumes:
      - ./MODEL/migration/src/main/resources/game-score/migration/:/flyway/sql
    depends_on:
      - db
  db:
 #   image: mysql_8_0
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1
    ports:
      - 3307:3306
