DROP TABLE IF EXISTS `CONF_PARAM`
;

CREATE TABLE IF NOT EXISTS `CONF_PARAM` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PARAM_KEY` VARCHAR(45) NOT NULL,
  `PARAM_VALUE` VARCHAR(255) NOT NULL,
  `CATEGORY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
;

INSERT INTO `conf_param` VALUES (1,'SERVER_ROOT_URL','https://kohlantstats.com','INFRASTRUCTURE')
;
INSERT INTO `conf_param` VALUES (2,'META_BINARY_TYPE_1','picture_1','META_BINARY_TYPE')
;
INSERT INTO `conf_param` VALUES (3,'META_BINARY_TYPE_2','picture_2','META_BINARY_TYPE')
;
INSERT INTO `conf_param` VALUES (4,'META_BINARY_TYPE_3','picture_3','META_BINARY_TYPE')
;
