call add_participant('les-quatre-terres', 'François', 'Zabalo', 'francois-2020', 'M', 47, null, 24, 'Pyrénées-Atlantiques', 'Négociant en matériaux');
call add_participant('les-quatre-terres', 'Carole', 'Collado', 'carole-2020', 'F', 52, null, 23, 'Bouches-du-Rhône', 'En recherche d''emploi');
call add_participant('les-quatre-terres', 'Samuel', 'Degoute', 'samuel-2020', 'M', 39, '1980-07-25', 22, 'Hauts-de-Seine', 'Coach mental');
call add_participant('les-quatre-terres', 'Diane', 'Goulesque-Perez', 'diane-2020', 'F', 25, null, 21, 'Pyrénées-Atlantiques', 'Agent immobilier');
call add_participant('les-quatre-terres', 'Estelle', 'Fabrice', 'estelle-2020', 'F', 47, null, 20, 'Seine-Maritime', 'Conseillère en insertion professionnelle');
call add_participant('les-quatre-terres', 'Mathieu', 'Blanchard', 'mathieu-2020', 'M', 31, '1987-12-03', 19, 'Vaucluse', 'Coureur professionnel');
call add_participant('les-quatre-terres', 'Adrien', 'Ferreira', 'adrien-2020', 'M', 30, null, 18, 'Paris', 'Ingénieur ferroviaire');
call add_participant('les-quatre-terres', 'Aubin', 'Bligny', 'aubin-2020', 'M', 23, '1995-12-13', 17, 'Gers', 'Agent immobilier');
call add_participant('les-quatre-terres', 'Sébastien', 'Aberlenc', 'sebastien-2020', 'M', 37, null, 16, 'Ardèche', 'Agent municipal');
call add_participant('les-quatre-terres', 'Marie-France', 'Schieber', 'marie-france-2020', 'F', 49, null, 15, 'Nord', 'Bouchère');
call add_participant('les-quatre-terres', 'Bertrand-Kamal', 'Loudrhiri', 'bertrand-kamal-2020', 'M', 30, '1989-09-11', 14, 'Côte d''Or', 'Animateur');
call add_participant('les-quatre-terres', 'Hadja', 'Cissé', 'hadja-2020', 'F', 28, '1991-03-07', 13, 'Marne', 'Handballeuse professionnelle');
call add_participant('les-quatre-terres', 'Joaquina', 'Glaud', 'joaquina-2020', 'F', 38, '1981-01-04', 12, 'Rhône', 'Boulangère');
call add_participant('les-quatre-terres', 'Jody', 'Favier', 'jody-2020', 'F', 32, null, 11, 'Charente-Maritime', 'Ostréicultrice');
call add_participant('les-quatre-terres', 'Laurent', 'Affri', 'laurent-2020', 'M', 48, '1970-12-05', 10, 'Isère', 'Professeur d''histoire-géographie');
call add_participant('les-quatre-terres', 'Alix', 'Noblat', 'alix-2020', 'F', 28, '1991-01-15', 9, 'Bouches-du-Rhône', 'Coach sportive et Pompier Volontaire');
call add_participant('les-quatre-terres', 'Fabrice', 'Pietrzak', 'fabrice-2020', 'M', 54, null, 8, 'Nord', 'Garagiste');
call add_participant('les-quatre-terres', 'Ava', 'Maisini', 'ava-2020', 'F', 26, '1993-11-12', 7, 'Corse', 'Propriétaire d''un fast-food');
call add_participant('les-quatre-terres', 'Angélique', 'Ti', 'angelique-2020', 'F', 26, '1993-03-13', 6, 'Hauts-de-Seine', 'Serveuse');
call add_participant('les-quatre-terres', 'Dorian', 'Louvet', 'dorian-2020', 'M', 30, '1989-10-02', 5, 'Calvados', 'Contrôleur de train');
call add_participant('les-quatre-terres', 'Lola', 'Besse', 'lola-2020', 'F', 23, null, 4, 'Pas-de-Calais', 'Étudiante en marketing');
call add_participant('les-quatre-terres', 'Loïc', 'Riowal', 'loic-2020', 'M', 20, null, 3, 'Savoie', 'Intérimaire');
call add_participant('les-quatre-terres', 'Brice', 'Petit', 'brice-2020', 'M', 22, '1997-01-03', 2, 'Creuse', 'Animateur de radio');
call add_participant('les-quatre-terres', 'Alexandra', 'Pornet', 'alexandra-2020', 'F', 30, null, 1, 'Ain', 'Comptable');
